- name: Application Services (AS3) playbook
  hosts: tag_Role_bigip
  connection: local
  vars_files: "{{ setupfile }}"

  tasks:
    - name: Check if necessary input parameters are defined
      assert:
        that:
          - atc.tenant is defined
          - atc.application is defined
          - scenario is defined

    - name: Set connection provider for BIG-IP tasks
      set_fact:
        provider:
          server: "{{ public_dns_name }}"
          server_port: 8443
          user: "{{ bigip.admin_user }}"
          password: "{{ bigip.admin_password }}"
          validate_certs: false          

    - name: Fetch AWS credentials (needed for auto-discovery)
      shell: aws configure get aws_access_key_id
      register: aws_access_key_id
      changed_when: false

    - name: Fetch AWS credentials (needed for auto-discovery)
      shell: aws configure get aws_secret_access_key
      register: aws_secret_access_key
      changed_when: false

    - name: Register AWS credentials as facts
      set_fact: 
        aws_access_key_id={{ aws_access_key_id.stdout }}
        aws_secret_access_key={{ aws_secret_access_key.stdout }}

    - name: Wait for BIG-IP to be ready to take configuration
      bigip_wait:
        timeout: 600
        provider: "{{ provider }}"

    ##########################
    # Perform AS3 Deployment #
    ##########################

    - name: Process jinja template and store result for artifact storage (auto pool)
      template:
        src: "templates/as3/auto/{{ scenario }}.json.j2"
        dest: "{{ outputfolder }}/as3_auto_{{ scenario }}.json"
        mode: 0644
      tags: deploy
      
    - name: Perform AS3 deployment (auto pool)
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        atc_declaration_file: "{{ outputfolder }}/as3_auto_{{ scenario }}.json"
        atc_delay: 10
        atc_retries: 5
      tags: deploy

    - name: Store result of AS3 deployment (auto pool)
      copy:
        content: |
          {{ (atc_AS3_status.json is defined) | ternary(atc_AS3_status.json | to_nice_json(indent=2), atc_AS3_status.content) }}
        dest: "{{ outputfolder }}/as3_auto_{{ scenario }}_result.json"
      tags: deploy

    ########################
    # Perform AS3 Undeploy #
    ########################
    - name: Process jinja template and store result for artifact storage
      template:
        src: templates/as3/remove_tenant.json.j2
        dest: "{{ outputfolder }}/as3_remove_tenant.json"
        mode: 0644
      tags: undeploy
  
    - name: Perform AS3 removal
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        atc_declaration_file: "{{ outputfolder }}/as3_remove_tenant.json"
        atc_delay: 10
        atc_retries: 10
      tags: undeploy

    - name: Store result of AS3 removal for artifact storage
      copy:
        content: |
          {{ (atc_AS3_status.json is defined) | ternary(atc_AS3_status.json | to_nice_json(indent=2), atc_AS3_status.content) }}
        dest: "{{ outputfolder }}/as3_remove_tenant_result.json"
      tags: undeploy

  ####################################
  # Manual verification on BIG-IP(s) #
  ####################################
  post_tasks:
    - name: Final result verification on BIG-IP 
      debug:
        msg: >
          Verify on BIG-IP if your desired result was achieved
            > Admin UI : https://{{ public_dns_name }}:8443
            > REST URI : https://{{ public_dns_name }}:8443/mgmt/shared/appsvcs/declare
            > DOCS URL   : https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest
            > SCHEMA REF : https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html
            > GITHUB SRC : https://github.com/F5Networks/f5-appsvcs-extension
