- name: Application Services (AS3) playbook
  hosts: tag_Role_bigip
  connection: local
  vars_files: "{{ setupfile }}"

  tasks:
    - name: Check if necessary input parameters are defined
      assert:
        that:
          - atc.tenant is defined
          - atc.application is defined
          - scenario is defined

    - name: Set connection provider for BIG-IP tasks
      set_fact:
        provider:
          server: "{{ public_dns_name }}"
          server_port: 8443
          user: "{{ bigip.admin_user }}"
          password: "{{ bigip.admin_password }}"
          validate_certs: false          

    - name: Wait for BIG-IP to be ready to take configuration
      bigip_wait:
        timeout: 600
        provider: "{{ provider }}"

    ##########################
    # Perform AS3 Deployment #
    ##########################

    ### Logging ###
    - name: Process jinja template and store result for artifact storage (log profile)
      template:
        src: "templates/as3/logging/logprofile.json.j2"
        dest: "{{ outputfolder }}/logprofile.json"
        mode: 0644
      tags: deploy

    - name: Perform AS3 deployment (log profile)
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        atc_declaration_file: "{{ outputfolder }}/logprofile.json"
        atc_delay: 10
        atc_retries: 5
      tags: deploy

    - name: Store result of AS3 deployment (log profile)
      copy:
        content: |
          {{ (atc_AS3_status.json is defined) | ternary(atc_AS3_status.json | to_nice_json(indent=2), atc_AS3_status.content) }}
        dest: "{{ outputfolder }}/logprofile_result.json"
      tags: deploy
    
    ### Application ###
    - name: Set initial lists to store host names and private ips of application servers (manual pool)
      set_fact:
        application_private_ips: []
      tags: deploy

    - name:  Get a list of private ip address of the target pool members for this application (manual pool)
      set_fact:
        application_private_ips: "{{ groups[group_name] | map('extract', hostvars, 'private_ip_address') | list }}" 
      vars:
        group_name: "tag_Application_{{ atc.application }}"
      tags: deploy

    - name: Process jinja template and store result for artifact storage (manual pool)
      template:
        src: "templates/as3/manual/{{ scenario }}_log.json.j2"
        dest: "{{ outputfolder }}/as3_manual_{{ scenario }}_log.json"
        mode: 0644
      tags: deploy
      
    - name: Perform AS3 deployment (manual pool)
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        atc_declaration_file: "{{ outputfolder }}/as3_manual_{{ scenario }}_log.json"
        atc_delay: 10
        atc_retries: 10
      tags: deploy

    - name: Store result of AS3 deployment (manual pool)
      copy:
        content: |
          {{ (atc_AS3_status.json is defined) | ternary(atc_AS3_status.json | to_nice_json(indent=2), atc_AS3_status.content) }}
        dest: "{{ outputfolder }}/as3_manual_{{ scenario }}_log_result.json"
      tags: deploy

    ########################
    # Perform AS3 Undeploy #
    ########################
    - name: Process jinja template and store result for artifact storage
      template:
        src: templates/as3/remove_tenant.json.j2
        dest: "{{ outputfolder }}/as3_remove_tenant.json"
        mode: 0644
      tags: undeploy
  
    - name: Perform AS3 removal
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        atc_declaration_file: "{{ outputfolder }}/as3_remove_tenant.json"
        atc_delay: 10
        atc_retries: 5
      tags: undeploy

    - name: Store result of AS3 removal for artifact storage
      copy:
        content: |
          {{ (atc_AS3_status.json is defined) | ternary(atc_AS3_status.json | to_nice_json(indent=2), atc_AS3_status.content) }}
        dest: "{{ outputfolder }}/as3_remove_tenant_result.json"
      tags: undeploy

  ####################################
  # Manual verification on BIG-IP(s) #
  ####################################
  post_tasks:
    - name: Final result verification on BIG-IP 
      debug:
        msg: >
          Verify on BIG-IP if your desired result was achieved
            > Admin UI : https://{{ public_dns_name }}:8443
            > REST URI : https://{{ public_dns_name }}:8443/mgmt/shared/appsvcs/declare
            > DOCS URL   : https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest
            > SCHEMA REF : https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html
            > GITHUB SRC : https://github.com/F5Networks/f5-appsvcs-extension
